keys:
  - &IKLAZV23 age1580c6m75egpzw2qyg0jpjm0juj3mefgg9a7825vg4x8qk3dzwdyqwe2vw3
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *IKLAZV23
