keys:
  - &IKLGFNAVMPRD001 age1mah9qvmekkz683cw0ge6s2cwyzk7knls6mm787p7g2gu9fr3qsqqmc4ezd
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *IKLGFNAVMPRD001
